language: python
python:
  - "2.7"
env:
  global:
    - DEBUG=True
services: 
  - postgresql
install:
  - pip install -r requirements.txt
before_script:
  - psql -c "create database travis_ci_test;" -U postgres
  - cd landing
  - python manage.py migrate --noinput
  - python manage.py syncdb --noinput
script:
  - python manage.py test